# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: axibase/checkout@v2
    - name: Set up JDK 11
      uses: axibase/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run tests in Docker
      run: |
        ./run_atsd_container.sh "-p8443:8443 -p8081:8081" jdbc_test_$(date +%s%N | cut -b1-13) axibase axibase
        mvn package -B -Dinsert.wait=3000 --fail-at-end
        
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [ spelling_retext, spelling_yandex, links, style, anchors ]

    steps:
      - uses: axibase/checkout@v2
        with:
          fetch-depth: 0
      - name: Running ${{ matrix.linter }} linter
        uses: axibase/docs-linter@v1
        with:
          linter: ${{ matrix.linter }}
